name: coverage

on: ["push", "pull_request"]

env:
  FOUNDRY_PROFILE: ci

jobs:
  forge:
    strategy:
      fail-fast: true
    permissions:
      pull-requests: write
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge test with gas report
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
        run: |
          forge test --gas-report
        id: test
